// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCliente(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) {
  return window['go']['main']['App']['CreateCliente'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
}

export function DeleteCliente(arg1) {
  return window['go']['main']['App']['DeleteCliente'](arg1);
}

export function GetClienteByID(arg1) {
  return window['go']['main']['App']['GetClienteByID'](arg1);
}

export function GetClientes(arg1) {
  return window['go']['main']['App']['GetClientes'](arg1);
}

export function GetLogoURL(arg1) {
  return window['go']['main']['App']['GetLogoURL'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function RestoreCliente(arg1) {
  return window['go']['main']['App']['RestoreCliente'](arg1);
}

export function UpdateCliente(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12) {
  return window['go']['main']['App']['UpdateCliente'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
}

export function UploadLogo(arg1, arg2) {
  return window['go']['main']['App']['UploadLogo'](arg1, arg2);
}
