// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalcularTotalesCotizacion(arg1:number,arg2:number,arg3:number,arg4:number):Promise<Record<string, any>>;

export function CreateCliente(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string,arg11:string):Promise<Record<string, any>>;

export function CreateCotizacion(arg1:number,arg2:number,arg3:number,arg4:string,arg5:string,arg6:number,arg7:string,arg8:string,arg9:number,arg10:string,arg11:string,arg12:string,arg13:string,arg14:number,arg15:number,arg16:number):Promise<Record<string, any>>;

export function CreateCotizacionFromProyecto(arg1:number,arg2:number):Promise<Record<string, any>>;

export function CreateProyecto(arg1:number,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function DeleteCliente(arg1:number):Promise<Record<string, any>>;

export function DeleteCotizacion(arg1:number):Promise<Record<string, any>>;

export function DeleteProyecto(arg1:number):Promise<Record<string, any>>;

export function DownloadCotizacionPDF(arg1:number,arg2:string):Promise<Record<string, any>>;

export function GetClienteByID(arg1:number):Promise<Record<string, any>>;

export function GetClientes(arg1:boolean):Promise<Record<string, any>>;

export function GetCotizacionByID(arg1:number):Promise<Record<string, any>>;

export function GetCotizacionFull(arg1:number):Promise<Record<string, any>>;

export function GetCotizacionPagos(arg1:number):Promise<Record<string, any>>;

export function GetCotizacionesRecientes(arg1:number):Promise<Record<string, any>>;

export function GetLogoURL(arg1:number):Promise<Record<string, any>>;

export function GetProyectoByID(arg1:number):Promise<Record<string, any>>;

export function GetProyectos(arg1:number,arg2:boolean):Promise<Record<string, any>>;

export function HasCotizacionChanges(arg1:number):Promise<Record<string, any>>;

export function OpenFile():Promise<Record<string, any>>;

export function RestoreCliente(arg1:number):Promise<Record<string, any>>;

export function RestoreProyecto(arg1:number):Promise<Record<string, any>>;

export function SearchCotizaciones(arg1:string):Promise<Record<string, any>>;

export function UpdateCliente(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string,arg11:string,arg12:string):Promise<Record<string, any>>;

export function UpdateCotizacion(arg1:number,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string,arg7:number,arg8:string,arg9:string,arg10:string,arg11:string,arg12:number,arg13:number,arg14:number):Promise<Record<string, any>>;

export function UpdateProyecto(arg1:number,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function UploadLogo(arg1:number,arg2:string):Promise<Record<string, any>>;
