// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalcularTotalesCotizacion(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CalcularTotalesCotizacion'](arg1, arg2, arg3, arg4);
}

export function CreateCliente(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) {
  return window['go']['main']['App']['CreateCliente'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
}

export function CreateCotizacion(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16) {
  return window['go']['main']['App']['CreateCotizacion'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16);
}

export function CreateCotizacionFromProyecto(arg1, arg2) {
  return window['go']['main']['App']['CreateCotizacionFromProyecto'](arg1, arg2);
}

export function CreateProyecto(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateProyecto'](arg1, arg2, arg3, arg4);
}

export function DeleteCliente(arg1) {
  return window['go']['main']['App']['DeleteCliente'](arg1);
}

export function DeleteCotizacion(arg1) {
  return window['go']['main']['App']['DeleteCotizacion'](arg1);
}

export function DeleteProyecto(arg1) {
  return window['go']['main']['App']['DeleteProyecto'](arg1);
}

export function DownloadCotizacionPDF(arg1, arg2) {
  return window['go']['main']['App']['DownloadCotizacionPDF'](arg1, arg2);
}

export function GetClienteByID(arg1) {
  return window['go']['main']['App']['GetClienteByID'](arg1);
}

export function GetClientes(arg1) {
  return window['go']['main']['App']['GetClientes'](arg1);
}

export function GetCotizacionByID(arg1) {
  return window['go']['main']['App']['GetCotizacionByID'](arg1);
}

export function GetCotizacionFull(arg1) {
  return window['go']['main']['App']['GetCotizacionFull'](arg1);
}

export function GetCotizacionPagos(arg1) {
  return window['go']['main']['App']['GetCotizacionPagos'](arg1);
}

export function GetCotizacionesRecientes(arg1) {
  return window['go']['main']['App']['GetCotizacionesRecientes'](arg1);
}

export function GetLogoURL(arg1) {
  return window['go']['main']['App']['GetLogoURL'](arg1);
}

export function GetProyectoByID(arg1) {
  return window['go']['main']['App']['GetProyectoByID'](arg1);
}

export function GetProyectos(arg1, arg2) {
  return window['go']['main']['App']['GetProyectos'](arg1, arg2);
}

export function HasCotizacionChanges(arg1) {
  return window['go']['main']['App']['HasCotizacionChanges'](arg1);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function RestoreCliente(arg1) {
  return window['go']['main']['App']['RestoreCliente'](arg1);
}

export function RestoreProyecto(arg1) {
  return window['go']['main']['App']['RestoreProyecto'](arg1);
}

export function SearchCotizaciones(arg1) {
  return window['go']['main']['App']['SearchCotizaciones'](arg1);
}

export function UpdateCliente(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12) {
  return window['go']['main']['App']['UpdateCliente'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
}

export function UpdateCotizacion(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14) {
  return window['go']['main']['App']['UpdateCotizacion'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14);
}

export function UpdateProyecto(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateProyecto'](arg1, arg2, arg3, arg4);
}

export function UploadLogo(arg1, arg2) {
  return window['go']['main']['App']['UploadLogo'](arg1, arg2);
}
