import React, { useState, useEffect } from 'react';
import { Alert, Spinner } from 'react-bootstrap';
import ClientesList from './ClientesList';
import ClienteForm from './ClienteForm';
import { Cliente, ClienteFormData, ClienteFormState, ClientesListState } from '../../types/api';

// Import Wails methods - these will be generated by wails dev
declare const GetClientes: (includeInactive: boolean) => Promise<any>;
declare const GetClienteByID: (id: number) => Promise<any>;
declare const CreateCliente: (nombre: string, nombreComercial: string, numero: string, correo: string, direccion: string, ciudad: string, provincia: string, telefono: string, representante: string, correoRepresentante: string, tipoFactura: string) => Promise<any>;
declare const UpdateCliente: (id: number, nombre: string, nombreComercial: string, numero: string, correo: string, direccion: string, ciudad: string, provincia: string, telefono: string, representante: string, correoRepresentante: string, tipoFactura: string) => Promise<any>;
declare const DeleteCliente: (id: number) => Promise<any>;
declare const RestoreCliente: (id: number) => Promise<any>;
declare const UploadLogo: (id: number, filePath: string) => Promise<any>;
declare const GetLogoURL: (id: number) => Promise<any>;

const ClientesPage: React.FC = () => {
  // List state
  const [listState, setListState] = useState<ClientesListState>({
    clientes: [],
    filteredClientes: [],
    searchTerm: '',
    idFilter: '',
    includeInactive: false,
    isLoading: false,
    selectedCliente: null,
  });

  // Form state
  const [formState, setFormState] = useState<ClienteFormState>({
    formData: {
      id: null,
      nombre: '',
      nombre_comercial: '',
      numero: '',
      correo: '',
      direccion: '',
      ciudad: '',
      provincia: '',
      telefono: '',
      representante: '',
      correo_representante: '',
      tipo_factura: 'NCFC',
    },
    isNew: true,
    isLoading: false,
    errors: {},
    logoFile: null,
    logoPreview: null,
  });

  // Alert state
  const [alert, setAlert] = useState<{ show: boolean; variant: string; message: string }>({
    show: false,
    variant: 'success',
    message: '',
  });

  // Load clientes on component mount
  useEffect(() => {
    loadClientes();
  }, [listState.includeInactive]);

  const loadClientes = async () => {
    setListState(prev => ({ ...prev, isLoading: true }));
    try {
      const result = await GetClientes(listState.includeInactive);
      if (result.success) {
        setListState(prev => ({
          ...prev,
          clientes: result.data || [],
          isLoading: false,
        }));
      } else {
        showAlert('danger', `Error al cargar clientes: ${result.error}`);
        setListState(prev => ({ ...prev, isLoading: false }));
      }
    } catch (error) {
      showAlert('danger', `Error al cargar clientes: ${error}`);
      setListState(prev => ({ ...prev, isLoading: false }));
    }
  };

  const showAlert = (variant: string, message: string) => {
    setAlert({ show: true, variant, message });
    setTimeout(() => {
      setAlert(prev => ({ ...prev, show: false }));
    }, 5000);
  };

  const handleClienteSelect = (cliente: Cliente) => {
    setListState(prev => ({ ...prev, selectedCliente: cliente }));
    setFormState(prev => ({
      ...prev,
      isNew: false,
      formData: {
        id: cliente.id,
        nombre: cliente.nombre,
        nombre_comercial: cliente.nombre_comercial,
        numero: cliente.numero,
        correo: cliente.correo,
        direccion: cliente.direccion,
        ciudad: cliente.ciudad,
        provincia: cliente.provincia,
        telefono: cliente.telefono,
        representante: cliente.representante,
        correo_representante: cliente.correo_representante,
        tipo_factura: cliente.tipo_factura,
      },
      errors: {},
    }));
    loadLogoPreview(cliente.id);
  };

  const handleNewCliente = () => {
    setListState(prev => ({ ...prev, selectedCliente: null }));
    setFormState({
      formData: {
        id: null,
        nombre: '',
        nombre_comercial: '',
        numero: '',
        correo: '',
        direccion: '',
        ciudad: '',
        provincia: '',
        telefono: '',
        representante: '',
        correo_representante: '',
        tipo_factura: 'NCFC',
      },
      isNew: true,
      isLoading: false,
      errors: {},
      logoFile: null,
      logoPreview: null,
    });
  };

  const handleIncludeInactiveChange = (include: boolean) => {
    setListState(prev => ({ ...prev, includeInactive: include }));
  };

  const loadLogoPreview = async (clienteId: number) => {
    try {
      const result = await GetLogoURL(clienteId);
      if (result.success && result.data?.path) {
        setFormState(prev => ({
          ...prev,
          logoPreview: result.data.path,
        }));
      }
    } catch (error) {
      // Logo not found or error - this is not critical
      console.log('Logo not found for cliente:', clienteId);
    }
  };

  const handleSave = async (formData: ClienteFormData, logoFile: File | null) => {
    setFormState(prev => ({ ...prev, isLoading: true, errors: {} }));

    try {
      let result;
      if (formState.isNew) {
        // Create new cliente
        result = await CreateCliente(
          formData.nombre,
          formData.nombre_comercial,
          formData.numero,
          formData.correo,
          formData.direccion,
          formData.ciudad,
          formData.provincia,
          formData.telefono,
          formData.representante,
          formData.correo_representante,
          formData.tipo_factura
        );
      } else {
        // Update existing cliente
        result = await UpdateCliente(
          formData.id!,
          formData.nombre,
          formData.nombre_comercial,
          formData.numero,
          formData.correo,
          formData.direccion,
          formData.ciudad,
          formData.provincia,
          formData.telefono,
          formData.representante,
          formData.correo_representante,
          formData.tipo_factura
        );
      }

      if (result.success) {
        showAlert('success', formState.isNew ? 'Cliente creado exitosamente' : 'Cliente actualizado exitosamente');
        await loadClientes();
        if (formState.isNew) {
          handleNewCliente();
        }
      } else {
        showAlert('danger', `Error al guardar: ${result.error}`);
      }
    } catch (error) {
      showAlert('danger', `Error al guardar: ${error}`);
    } finally {
      setFormState(prev => ({ ...prev, isLoading: false }));
    }
  };

  const handleCancel = () => {
    handleNewCliente();
  };

  const handleDelete = async (id: number) => {
    if (window.confirm('¿Está seguro de que desea eliminar este cliente?')) {
      try {
        const result = await DeleteCliente(id);
        if (result.success) {
          showAlert('success', 'Cliente eliminado exitosamente');
          await loadClientes();
          handleNewCliente();
        } else {
          showAlert('danger', `Error al eliminar: ${result.error}`);
        }
      } catch (error) {
        showAlert('danger', `Error al eliminar: ${error}`);
      }
    }
  };

  const handleLogoChange = (file: File) => {
    setFormState(prev => ({
      ...prev,
      logoFile: file,
      logoPreview: URL.createObjectURL(file),
    }));
  };

  return (
    <div>
      <h2 className="mb-4">
        <i className="bi bi-people me-2"></i>
        Gestión de Clientes
      </h2>

      {/* Alert */}
      {alert.show && (
        <Alert
          variant={alert.variant}
          dismissible
          onClose={() => setAlert(prev => ({ ...prev, show: false }))}
          className="mb-4"
        >
          {alert.message}
        </Alert>
      )}

      {/* Clientes List */}
      <ClientesList
        clientes={listState.clientes}
        isLoading={listState.isLoading}
        selectedCliente={listState.selectedCliente}
        includeInactive={listState.includeInactive}
        onClienteSelect={handleClienteSelect}
        onNewCliente={handleNewCliente}
        onIncludeInactiveChange={handleIncludeInactiveChange}
      />

      {/* Cliente Form */}
      <ClienteForm
        cliente={listState.selectedCliente}
        isNew={formState.isNew}
        isLoading={formState.isLoading}
        errors={formState.errors}
        logoPreview={formState.logoPreview}
        onSave={handleSave}
        onCancel={handleCancel}
        onDelete={handleDelete}
        onLogoChange={handleLogoChange}
      />
    </div>
  );
};

export default ClientesPage;
