// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAuthStatus() {
  return window['go']['main']['App']['CheckAuthStatus']();
}

export function CreateProposal(arg1) {
  return window['go']['main']['App']['CreateProposal'](arg1);
}

export function DeleteProposal(arg1) {
  return window['go']['main']['App']['DeleteProposal'](arg1);
}

export function DownloadProposal(arg1, arg2) {
  return window['go']['main']['App']['DownloadProposal'](arg1, arg2);
}

export function GenerateHTML(arg1) {
  return window['go']['main']['App']['GenerateHTML'](arg1);
}

export function GeneratePDF(arg1, arg2) {
  return window['go']['main']['App']['GeneratePDF'](arg1, arg2);
}

export function GetProposals() {
  return window['go']['main']['App']['GetProposals']();
}

export function ModifyProposal(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ModifyProposal'](arg1, arg2, arg3, arg4);
}

export function OpenDirectory() {
  return window['go']['main']['App']['OpenDirectory']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function RegenerateProposal(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RegenerateProposal'](arg1, arg2, arg3, arg4);
}

export function UpdateTitleSubtitle(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTitleSubtitle'](arg1, arg2, arg3);
}
