// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {propapi} from '../models';

export function CheckAuthStatus():Promise<Record<string, any>>;

export function CreateProposal(arg1:propapi.TextGenerationRequest):Promise<propapi.TextGenerationResponse>;

export function DeleteProposal(arg1:string):Promise<Record<string, any>>;

export function DownloadProposal(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GenerateHTML(arg1:string):Promise<Record<string, any>>;

export function GeneratePDF(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetProposals():Promise<Array<propapi.Proposal>>;

export function ModifyProposal(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function OpenDirectory():Promise<Record<string, any>>;

export function OpenFile(arg1:string):Promise<Record<string, any>>;

export function RegenerateProposal(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function UpdateTitleSubtitle(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;
